notifications:
  email:
    recipients:
      - matleses0@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

language: python

python:
  - "3.5"

env:
  - DJANGO_SETTINGS_MODULE="probemanager.settings.dev"

os:
  - linux

sudo: required

branches:
  only:
    - master

services:
  - postgresql

install:
  - ./travis.sh

script:
  - flake8 probemanager/ --config=.flake8
  - coverage erase
  - coverage run --source=probemanager/home,probemanager/rules probemanager/runtests.py --app home rules
  - coverage report -i --skip-covered
