notifications:
  email:
    recipients:
    - matthieu@treussart.com
    on_success: change
    on_failure: always
language: python
python:
- '3.5'
- '3.6'
env:
  matrix:
    - SURICATA_VERSION="4.0.4"
  global:
    - MOZ_HEADLESS=1
os:
- linux
sudo: required
branches:
  only:
  - master
  - develop
services:
- postgresql
- rabbitmq
install:
- "./install.sh prod ."
script:
- "./test.sh"
before_install:
- mkdir probemanager/ssh_keys
- openssl aes-256-cbc -K $encrypted_d9bd8970c4fe_key -iv $encrypted_d9bd8970c4fe_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
addons:
  firefox: latest
deploy:
  provider: pages
  local-dir: docs/_build/html
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: gh-pages
