notifications:
  email:
    recipients:
    - matthieu@treussart.com
    on_success: change
    on_failure: always
language: python
python:
- '3.5'
- '3.6'
env:
- DJANGO_SETTINGS_MODULE="probemanager.settings.dev"
os:
- linux
sudo: required
branches:
  only:
  - master
  - develop
services:
- postgresql
- rabbitmq
install:
- "./install.sh travis"
script:
- "./test.sh"
before_install:
- mkdir probemanager/ssh_keys
- openssl aes-256-cbc -K $encrypted_d9bd8970c4fe_key -iv $encrypted_d9bd8970c4fe_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
