notifications:
  email:
    recipients:
      - matleses0@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

language: python

python:
  - "3.5"

os:
  - linux

branches:
  only:
    - master

# command to run tests
script:
  - flake8 probemanager/ --config=.flake8
  - ./install.sh travis
  - coverage erase
  - coverage run --source=probemanager/home probemanager/runtests.py --app home
  - coverage report -i --skip-covered
