notifications:
  email:
    recipients:
    - matleses0@gmail.com
    on_success: change
    on_failure: always
language: python
python:
- '3.5'
env:
- DJANGO_SETTINGS_MODULE="probemanager.settings.dev"
os:
- linux
sudo: required
branches:
  only:
  - master
services:
- postgresql
- rabbitmq
install:
- "./install.sh travis"
script:
- "./test.sh"
before_install:
- mkdir probemanager/ssh_keys
- openssl aes-256-cbc -K $encrypted_d9bd8970c4fe_key -iv $encrypted_d9bd8970c4fe_iv
  -in .coveralls.yml.enc -out .coveralls.yml -d
- openssl aes-256-cbc -K $encrypted_d9bd8970c4fe_key -iv $encrypted_d9bd8970c4fe_iv
  -in test-core-secrets.ini.enc -out probemanager/core/fixtures/test-core-secrets.ini
  -d
- openssl aes-256-cbc -K $encrypted_d9bd8970c4fe_key -iv $encrypted_d9bd8970c4fe_iv
  -in test-core-secrets.json.enc -out probemanager/core/fixtures/test-core-secrets.json
  -d
- openssl aes-256-cbc -K $encrypted_d9bd8970c4fe_key -iv $encrypted_d9bd8970c4fe_iv
  -in travis-treussart.com_rsa.enc -out probemanager/ssh_keys/travis-treussart.com_rsa
  -d
